// /** @type {import('tailwindcss').Config} */
// module.exports = {
//   content: [
//     "./app/**/*.{js,ts,jsx,tsx,mdx}",
//     "./components/**/*.{js,ts,jsx,tsx,mdx}",
//     "./lib/**/*.{js,ts,jsx,tsx}",
//   ],
//   theme: {
//     extend: {
//       colors: {
//         bg:     "#020c12",
//         bg2:    "#030e16",
//         bg3:    "#071520",
//         card:   "#081c2c",
//         card2:  "#0c2236",
//         cyan1:  "#00b4d8",
//         cyan2:  "#22d3ee",
//         cyan3:  "#67e8f9",
//         blue1:  "#0077aa",
//         blue2:  "#00a8cc",
//         teal1:  "#0d9488",
//         teal2:  "#14b8a6",
//         amber1: "#f59e0b",
//         amber2: "#fbbf24",
//         gray1:  "#7a9db0",
//         gray2:  "#a8c8dc",
//       },
//       fontFamily: {
//         syne:  ["Syne", "sans-serif"],
//         inter: ["Inter", "sans-serif"],
//       },
//       backgroundImage: {
//         "grad-cyan":  "linear-gradient(135deg, #00b4d8, #22d3ee)",
//         "grad-brand": "linear-gradient(135deg, #00b4d8, #22d3ee, #67e8f9)",
//         "grad-amber": "linear-gradient(135deg, #f59e0b, #fbbf24)",
//         "grad-cyan-btn": "linear-gradient(135deg, #00b4d8, #22d3ee)",
//         "grad-amber-btn": "linear-gradient(135deg, #f59e0b, #fbbf24)",
//       },
//       animation: {
//         "spin-slow":   "spin 35s linear infinite",
//         "spin-medium": "spin 25s linear infinite reverse",
//         "spin-fast":   "spin 15s linear infinite",
//         "ticker":      "tickScroll 22s linear infinite",
//         "blink-dot":   "blinkDot 1.2s ease-in-out infinite",
//         "cursor-blink":"cursorBlink .7s infinite",
//         "wa-float":    "waFloat 3s ease-in-out infinite",
//         "pre-fill":    "barFill 2.2s ease forwards",
//         "pre-spin":    "spin 1s linear infinite",
//         "fade-up":     "fadeUp 0.9s ease both",
//         "fade-right":  "fadeRight 0.9s ease .15s both",
//         "about-rotate":"aboutGlow 10s linear infinite",
//         "bot-pulse":   "botPulse 3s ease-in-out infinite",
//         "msg-in":      "msgIn .3s ease both",
//         "typing-dot":  "typingDot 1.2s ease-in-out infinite",
//         "chat-open":   "chatOpen .3s cubic-bezier(.34,1.56,.64,1) both",
//       },
//       keyframes: {
//         tickScroll:   { from: { transform: "translateX(0)" }, to: { transform: "translateX(-50%)" } },
//         blinkDot:     { "0%,100%": { transform: "scale(1)", opacity: "1" }, "50%": { transform: "scale(1.8)", opacity: ".6" } },
//         cursorBlink:  { "50%": { opacity: "0" } },
//         waFloat:      { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
//         barFill:      { from: { width: "0" }, to: { width: "100%" } },
//         fadeUp:       { from: { opacity: "0", transform: "translateY(30px)" }, to: { opacity: "1", transform: "translateY(0)" } },
//         fadeRight:    { from: { opacity: "0", transform: "scale(0.9)" }, to: { opacity: "1", transform: "scale(1)" } },
//         aboutGlow:    { to: { transform: "rotate(360deg)" } },
//         botPulse:     { "0%,100%": { boxShadow: "0 8px 30px rgba(0,180,216,.5)" }, "50%": { boxShadow: "0 8px 40px rgba(0,180,216,.8), 0 0 0 10px rgba(0,180,216,.1)" } },
//         msgIn:        { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
//         typingDot:    { "0%,60%,100%": { transform: "translateY(0)", opacity: ".4" }, "30%": { transform: "translateY(-6px)", opacity: "1" } },
//         chatOpen:     { from: { opacity: "0", transform: "scale(0.8) translateY(20px)" }, to: { opacity: "1", transform: "scale(1) translateY(0)" } },
//       },
//       boxShadow: {
//         "cyan-sm":  "0 4px 20px rgba(0,180,216,.2)",
//         "cyan-md":  "0 20px 50px rgba(0,180,216,.2)",
//         "cyan-lg":  "0 30px 60px rgba(0,180,216,.25)",
//         "cyan-glow":"0 0 50px rgba(0,180,216,.25)",
//         "wa":       "0 6px 28px rgba(37,211,102,.5)",
//       },
//       borderColor: {
//         "cyan-border": "rgba(0,180,216,.18)",
//       },
//     },
//   },
//   plugins: [],
// }

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#020c12",
        bg2: "#030e16",
        bg3: "#071520",
        card: "#081c2c",
        card2: "#0c2236",
        cyan1: "#00b4d8",
        cyan2: "#22d3ee",
        cyan3: "#67e8f9",
        blue1: "#0077aa",
        blue2: "#00a8cc",
        teal1: "#0d9488",
        teal2: "#14b8a6",
        amber1: "#f59e0b",
        amber2: "#fbbf24",
        gray1: "#7a9db0",
        gray2: "#a8c8dc",
      },
      fontFamily: {
        syne: ["Syne", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "Inter", "sans-serif"], // ← default body font
      },
      backgroundImage: {
        "grad-cyan": "linear-gradient(135deg, #00b4d8, #22d3ee)",
        "grad-brand": "linear-gradient(135deg, #00b4d8, #22d3ee, #67e8f9)",
        "grad-amber": "linear-gradient(135deg, #f59e0b, #fbbf24)",
        "grad-cyan-btn": "linear-gradient(135deg, #00b4d8, #22d3ee)",
        "grad-amber-btn": "linear-gradient(135deg, #f59e0b, #fbbf24)",
      },
      animation: {
        "spin-slow": "spin 35s linear infinite",
        "spin-medium": "spin 25s linear infinite reverse",
        "spin-fast": "spin 15s linear infinite",
        ticker: "tickScroll 22s linear infinite",
        "blink-dot": "blinkDot 1.2s ease-in-out infinite",
        "cursor-blink": "cursorBlink .7s infinite",
        "wa-float": "waFloat 3s ease-in-out infinite",
        "pre-fill": "barFill 2.2s ease forwards",
        "pre-spin": "spin 1s linear infinite",
        "fade-up": "fadeUp 0.9s ease both",
        "fade-right": "fadeRight 0.9s ease .15s both",
        "about-rotate": "aboutGlow 10s linear infinite",
        "bot-pulse": "botPulse 3s ease-in-out infinite",
        "msg-in": "msgIn .3s ease both",
        "typing-dot": "typingDot 1.2s ease-in-out infinite",
        "chat-open": "chatOpen .3s cubic-bezier(.34,1.56,.64,1) both",
      },
      keyframes: {
        tickScroll: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
        blinkDot: {
          "0%,100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.8)", opacity: ".6" },
        },
        cursorBlink: { "50%": { opacity: "0" } },
        waFloat: {
          "0%,100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        barFill: { from: { width: "0" }, to: { width: "100%" } },
        fadeUp: {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeRight: {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        aboutGlow: { to: { transform: "rotate(360deg)" } },
        botPulse: {
          "0%,100%": { boxShadow: "0 8px 30px rgba(0,180,216,.5)" },
          "50%": {
            boxShadow:
              "0 8px 40px rgba(0,180,216,.8), 0 0 0 10px rgba(0,180,216,.1)",
          },
        },
        msgIn: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        typingDot: {
          "0%,60%,100%": { transform: "translateY(0)", opacity: ".4" },
          "30%": { transform: "translateY(-6px)", opacity: "1" },
        },
        chatOpen: {
          from: { opacity: "0", transform: "scale(0.8) translateY(20px)" },
          to: { opacity: "1", transform: "scale(1) translateY(0)" },
        },
      },
      boxShadow: {
        "cyan-sm": "0 4px 20px rgba(0,180,216,.2)",
        "cyan-md": "0 20px 50px rgba(0,180,216,.2)",
        "cyan-lg": "0 30px 60px rgba(0,180,216,.25)",
        "cyan-glow": "0 0 50px rgba(0,180,216,.25)",
        wa: "0 6px 28px rgba(37,211,102,.5)",
      },
      borderColor: {
        "cyan-border": "rgba(0,180,216,.18)",
      },
    },
  },
  plugins: [],
};
